#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /
    controller: App\Controller\HomeController::index

security_logout:
    path: /deconnexion
    controller: App\Controller\SecurityController::deconnexion

# config/routes.yaml
index:
    path: /
    controller: App\Controller\DefaultController::index

show_groupe:
    path: /showgroupe
    controller: App\Controller\GroupeController::show

create_groupe:
    path: /creategroupe
    controller: App\Controller\GroupeController::create
